algoritmo "Primeiro Programa"
// Função : Escreve "Olá Mundo" na Tela
// Autor : Marcos Fernando Borges
// Data : 17/01/2024
// Seção de Declarações 

var
msg: caracter

inicio
// Seção de Comandos 

Escreval ("")
Escreval (" ----------------------------------------- ")

         msg <- (" >> OLÁ MUNDO, ME LIVREI DA MALDICAO! ")

         Escreval (" MENSAGEM: " )
         Escreval (" >>")
         Escreval (msg)

Escreval (" ----------------------------------------- ")

fimalgoritmo
