Algoritmo "Primeiro Algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Utilizando atribuicao
// Autor(a)    : Marcos Fernando Borges
// Data atual  : 22/09/2024


Var
msg: caracter


Inicio


Escreval (" ------------------ ")
Escreval (" PRIMEIRO ALGORITMO ")
Escreval (" ------------------ ")
Escreval ("")

         msg <- (" Olá mundo! Me Livrei da Maldicao! ")

         Escreval (msg)


Fimalgoritmo